name: Deploy to ec2

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ssh into ec2
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
          chmod 600 ~/ssh_key
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@13.233.145.229 -t "cd /home/ubuntu/jwt/login_jwt/jwt_login && git pull origin master && pm2 restart jwt"