name: Deploy to ec2

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ssh into ec2
        run: |
          echo "${{secrets.SSH_PRIVATE_KEY}}" &> ~/ssh_key
          chmod 600 ~/ssh_key
          cat ~/ssh_key
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@13.201.18.204
      
      - name: pull the code
        run: |
          cd jwt/
          git pull https://github.com/chand7O22/jwt_login.git
      
      - name: restart the process
        run: |
          pm2 restart jwt   
